version: "2.1"

networks:
  pokenetwork:
    driver: bridge

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - pokenetwork
    links:
      - server
      - client
      - indexator

  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - pokenetwork
    depends_on:
      indexator:
        condition: service_healthy

  indexator:
    container_name: indexator
    restart: always
    build: ./indexator
    ports:
      - "8040:8040"
    networks:
      - pokenetwork
    depends_on:
       redis:
        condition: service_started
    healthcheck:
      test: curl -f http://localhost:8040/indexator/healthcheck || exit 1
      interval: 15s
      timeout: 1s
      retries: 5


  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "8080:8080"
    networks:
      - pokenetwork
    links:
      - server
    depends_on:
      server:
        condition: service_started

  redis:
    container_name: redis
    image: redis
    networks:
      - pokenetwork

  cron:
    container_name: cron
    build: cron
    networks:
      - pokenetwork
    depends_on:
      indexator:
        condition: service_healthy