version: "3"

networks:
  pokenetwork:
    driver: bridge

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - pokenetwork
    links:
      - server
      - client

  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - pokenetwork

  client:
    container_name: client
    restart: always
    build: ./client
    ports:
      - "8080:8080"
    networks:
      - pokenetwork
    links:
      - server

  redis:
    container_name: redis
    image: redis
    networks:
      - pokenetwork