export const CARDS_FETCHING = 'CARDS_FETCHING';
export const CARDS_RECEIVED = 'CARDS_RECEIVED';
export const CARDS_REQUESTED = 'CARDS_REQUESTED';
export const CARDS_ERROR = 'CARDS_ERROR';

export const PAGE_FETCHING = 'PAGE_FETCHING';
export const PAGE_RECEIVED = 'PAGE_RECEIVED';
export const PAGE_REQUESTED = 'PAGE_REQUESTED';
export const PAGE_ERROR = 'PAGE_ERROR';

export const RELATED_FETCHING = 'RELATED_FETCHING';
export const RELATED_RECEIVED = 'RELATED_RECEIVED';